export const REVERSE: 'REVERSE' = 'REVERSE';
export const FIBONACCI: 'FIBONACCI' = 'FIBONACCI';
export const SELECTION_SORT: 'SELECTION_SORT' = 'SELECTION_SORT';
export const BUBBLE_SORT: 'BUBBLE_SORT' = 'BUBBLE_SORT';
